version: '3.3'

services:
  go:
    image: ignatka89/docker-go-test-app:v1
    #build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
      - 9100:9100
    links:
      - redis
    environment:
      REDIS_ADDR: redis

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 5 1 --loglevel warning
    volumes:
      - cache:/data
  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:7.5.2
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
volumes:
  cache:
    driver: local
  prometheus:
