scrape_configs:
- job_name: myapp
  scrape_interval: 10s
  static_configs:
  - targets:
    - go:9100
- job_name: redis-exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'redis-exporter:9121'
